[package]
name = "doxing-emulator"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "Doxing emulator"
keywords = ["telegram", "bot", "entertainment"]
categories = ["command-line-utilities", "games", "security", "simulation"]
include = ["src", "README.md", "LICENSE"]
repository = "https://github.com/PRO-2684/doxing-emulator"
license = "MIT"
authors = ["PRO-2684"]

[dependencies]
env_logger = "0.11.8"
frankenstein = { version = "0.41.0", features = ["client-reqwest"] }
log = "0.4.27"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.0", features = ["rt-multi-thread", "macros"] }
toml = "0.8.23"

[[bin]]
name = "doxing-emulator"
required-features = ["cli"]

[features]
cli = []

[profile.release]
debug = false     # Disable debug information in release builds.
strip = true      # Automatically strip symbols from the binary.
lto = true        # Enable link-time optimization.
codegen-units = 1 # Set the number of codegen units to 1.

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
